--
-- PostgreSQL database dump
--

\restrict wBeyH8wdsT4au7bCSBJCyaQtTMuL2h6ElDwbMQQljqSUZc78qeFnm4wvzuoJ3C1

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: role_user; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.role_user AS ENUM (
    'super_admin',
    'report_viewer',
    'viewer'
);


ALTER TYPE public.role_user OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_models; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ai_models (
    id integer NOT NULL,
    filename text NOT NULL,
    display_name text NOT NULL,
    is_active boolean DEFAULT false NOT NULL
);


ALTER TABLE public.ai_models OWNER TO postgres;

--
-- Name: ai_models_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ai_models_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ai_models_id_seq OWNER TO postgres;

--
-- Name: ai_models_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ai_models_id_seq OWNED BY public.ai_models.id;


--
-- Name: cctv_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cctv_data (
    id bigint NOT NULL,
    name character varying NOT NULL,
    ip_address character varying,
    port integer DEFAULT 7441,
    token character varying,
    location character varying,
    area jsonb,
    enabled boolean DEFAULT false
);


ALTER TABLE public.cctv_data OWNER TO postgres;

--
-- Name: cctv_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cctv_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cctv_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cctv_scheduler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cctv_scheduler (
    id bigint NOT NULL,
    cctv_id bigint NOT NULL,
    day_of_week smallint NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    is_active boolean DEFAULT true,
    CONSTRAINT cctv_scheduler_day_of_week_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6))),
    CONSTRAINT valid_time_range CHECK (((start_time < end_time) OR (end_time = '00:00:00'::time without time zone)))
);


ALTER TABLE public.cctv_scheduler OWNER TO postgres;

--
-- Name: cctv_scheduler_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cctv_scheduler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cctv_scheduler_id_seq OWNER TO postgres;

--
-- Name: cctv_scheduler_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cctv_scheduler_id_seq OWNED BY public.cctv_scheduler.id;


--
-- Name: email_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.email_settings (
    id integer NOT NULL,
    smtp_host character varying(255) DEFAULT 'smtp.gmail.com'::character varying NOT NULL,
    smtp_port integer DEFAULT 587 NOT NULL,
    smtp_user character varying(255) NOT NULL,
    smtp_pass character varying(255) NOT NULL,
    smtp_from character varying(255) NOT NULL,
    enable_auto_email boolean DEFAULT false NOT NULL
);


ALTER TABLE public.email_settings OWNER TO postgres;

--
-- Name: email_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.email_settings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.email_settings_id_seq OWNER TO postgres;

--
-- Name: email_settings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.email_settings_id_seq OWNED BY public.email_settings.id;


--
-- Name: email_templates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.email_templates (
    id integer NOT NULL,
    template_key character varying(100) NOT NULL,
    subject_template text DEFAULT '[URGENT] Subject Email from PPE Detection'::text NOT NULL,
    body_template text DEFAULT '<!DOCTYPE html> <html> <head>   <meta charset="utf-8">   <style>     body { font-family: Arial, sans-serif; background:#f9f9f9; margin:0; padding:20px; }     .container { max-width: 680px; margin: auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }     .header { background: #4388CA; color: white; padding: 20px; text-align: center; }     .header h1 { margin:0; font-size:24px; }     .content { padding: 30px; line-height: 1.6; color: #333; }     .footer { background:#263238; color:#cfd8dc; padding:20px; text-align:center; font-size:13px; }   </style> </head> <body>   <div class="container">     <div class="header">       <h1>Email Template Subject</h1>     </div>      <div class="content">       <p>Email Template Body</p>      <div class="footer">       © 2025 PPE Detection System – PT. Summit Adyawinsa Indonesia     </div>   </div> </body> </html>   '::text NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.email_templates OWNER TO postgres;

--
-- Name: email_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.email_templates_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.email_templates_id_seq OWNER TO postgres;

--
-- Name: email_templates_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.email_templates_id_seq OWNED BY public.email_templates.id;


--
-- Name: general_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.general_settings (
    key text NOT NULL,
    value numeric NOT NULL,
    description text,
    min_value numeric DEFAULT 0,
    max_value numeric DEFAULT 9999
);


ALTER TABLE public.general_settings OWNER TO postgres;

--
-- Name: object_class; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.object_class (
    id bigint NOT NULL,
    name character varying NOT NULL,
    is_violation boolean DEFAULT false NOT NULL,
    color_r integer DEFAULT 255 NOT NULL,
    color_g integer DEFAULT 255 NOT NULL,
    color_b integer DEFAULT 255 NOT NULL,
    pair_id integer
);


ALTER TABLE public.object_class OWNER TO postgres;

--
-- Name: object_class_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.object_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.object_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_cctv_map; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_cctv_map (
    user_id uuid NOT NULL,
    cctv_id integer NOT NULL
);


ALTER TABLE public.user_cctv_map OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    username text NOT NULL,
    password text NOT NULL,
    full_name text,
    email text NOT NULL,
    role public.role_user DEFAULT 'viewer'::public.role_user NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: violation_daily_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.violation_daily_log (
    id bigint NOT NULL,
    log_date date NOT NULL,
    id_cctv bigint NOT NULL,
    id_violation bigint NOT NULL,
    total_violation bigint,
    latest_update timestamp with time zone
);


ALTER TABLE public.violation_daily_log OWNER TO postgres;

--
-- Name: violation_daily_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.violation_daily_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.violation_daily_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: violation_detection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.violation_detection (
    id bigint NOT NULL,
    id_cctv bigint,
    id_violation bigint,
    image text,
    "timestamp" timestamp with time zone
);


ALTER TABLE public.violation_detection OWNER TO postgres;

--
-- Name: violation_detection_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.violation_detection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.violation_detection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_models id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_models ALTER COLUMN id SET DEFAULT nextval('public.ai_models_id_seq'::regclass);


--
-- Name: cctv_scheduler id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cctv_scheduler ALTER COLUMN id SET DEFAULT nextval('public.cctv_scheduler_id_seq'::regclass);


--
-- Name: email_settings id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_settings ALTER COLUMN id SET DEFAULT nextval('public.email_settings_id_seq'::regclass);


--
-- Name: email_templates id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_templates ALTER COLUMN id SET DEFAULT nextval('public.email_templates_id_seq'::regclass);


--
-- Data for Name: ai_models; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ai_models (id, filename, display_name, is_active) FROM stdin;
1	ppe_detection_yolov12l.pt	YOLOv12 Large	f
2	ppe_detection_yolov12n.pt	YOLOv12 Nano	f
3	ppe_detection_rtdert.pt	RT-DERT	f
4	ppe_detection_first_ed.pt	YOLOv8 (First edition model)	f
5	ppe_detection_yolov12l_latest.pt	YOLOv12 Large (latest)	t
6	ppe_detection_yolov12m_latest.pt	YOLOv12 Medium	f
7	ppe_detection_yolov12n_latest.pt	YOLOv12 Nano (Latest)	f
\.


--
-- Data for Name: cctv_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cctv_data (id, name, ip_address, port, token, location, area, enabled) FROM stdin;
\.


--
-- Data for Name: cctv_scheduler; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cctv_scheduler (id, cctv_id, day_of_week, start_time, end_time, is_active) FROM stdin;
\.


--
-- Data for Name: email_settings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.email_settings (id, smtp_host, smtp_port, smtp_user, smtp_pass, smtp_from, enable_auto_email) FROM stdin;
\.


--
-- Data for Name: email_templates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.email_templates (id, template_key, subject_template, body_template, is_active) FROM stdin;
1	ppe_violation	[URGENT] PPE Violation: ${violation_name} at ${location}	<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="utf-8">\n  <style>\n    body { font-family: Arial, sans-serif; background:#f9f9f9; margin:0; padding:20px; }\n    .container { max-width: 680px; margin: auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }\n    .header { background: #d32f2f; color: white; padding: 20px; text-align: center; }\n    .header h1 { margin:0; font-size:24px; }\n    .content { padding: 30px; line-height: 1.6; color: #333; }\n    .alert { background:#fff3cd; padding:15px; border-left:5px solid #ffc107; border-radius:4px; margin:20px 0; }\n    table {width:100%; border-collapse:collapse; margin:10px 0;}\n    th {text-align:left; width:35%; font-weight:600; color:#555;}\n    .footer { background:#263238; color:#cfd8dc; padding:20px; text-align:center; font-size:13px; }\n    .btn { display:inline-block; background:#d32f2f; color:white; padding:12px 24px; text-decoration:none; border-radius:5px; margin-top:20px; font-weight:bold; }\n    img.attachment { max-width:100%; height:auto; border-radius:8px; margin-top:20px; box-shadow:0 2px 8px rgba(0,0,0,0.2); }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>PPE VIOLATION DETECTED</h1>\n    </div>\n\n    <div class="content">\n      <p>Dear Mr./Ms. <strong>$full_name</strong>,</p>\n\n      <p>A serious PPE violation has been automatically detected by AI system in your area of responsibility.</p>\n\n      <div class="alert">\n        <table>\n          <tr>\n            <th><strong>Violation Type</strong></th>\n            <td>:</td>\n            <td>${violation_name}</td>\n          </tr>\n          <tr>\n            <th><strong>CCTV Location</strong></th>\n            <td>:</td>\n            <td>${cctv_name} – (${location})</td>\n          </tr>\n          <tr>\n            <th><strong>Time of Incident</strong></th>\n            <td>:</td>\n            <td>${timestamp}</td>\n          </tr>\n        </table>\n      </div>\n\n      <p>Visual evidence is attached below. Please immediately take corrective action and provide guidance to personnel in the area.</p>\n\n      <hr style="margin:30px 0; border:none; border-top:1px dashed #ccc;">\n\n      <p style="font-size:12px; color:#777;">\n        This email was sent automatically by the PPE AI Monitoring System.<br>\n        If you received this email by mistake, please disregard it.\n      </p>\n    </div>\n\n    <div class="footer">\n      © 2025 PPE Detection System – PT. Summit Adyawinsa Indonesia\n    </div>\n  </div>\n</body>\n</html>\n  	t
8	violation_weekly_recap	[RECAP] Weekly PPE Violation Report Period ${start_date} to ${end_date}	<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset="utf-8">\n        <style>\n            body { font-family: Arial, sans-serif; background:#f9f9f9; margin:0; padding:20px; }\n            .container { max-width: 680px; margin: auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }\n            .header { background: #4388CA; color: white; padding: 20px; text-align: center; }\n            .header h1 { margin:0; font-size:24px; }\n            .content { padding: 30px; line-height: 1.6; color: #333; }\n            .info-box { background:#e3f2fd; padding:15px; border-left:5px solid #2196f3; border-radius:4px; margin:20px 0; }\n            table {width:100%; border-collapse:collapse; margin:10px 0;}\n            th {text-align:left; width:35%; font-weight:600; color:#555;}\n            .footer { background:#263238; color:#cfd8dc; padding:20px; text-align:center; font-size:13px; }\n            .btn { display:inline-block; background:#4388CA; color:white; padding:12px 24px; text-decoration:none; border-radius:5px; margin-top:20px; font-weight:bold; }\n        </style>\n    </head>\n    <body>\n        <div class="container">\n            <div class="header">\n                <h1>Weekly PPE Violation Summary Report</h1>\n            </div>\n\n            <div class="content">\n                <p>Dear Mr./Ms. <strong>${full_name}</strong>,</p>\n\n                <p>Below is a summary of the Weekly PPE Violation Report for the period below, which occurred on CCTV in your area of ​​responsibility.</p>\n                    \n                <div class="info-box">\n                    <table>\n                        <tr>\n                            <th><strong>Start Date</strong></th>\n                            <td>:</td>\n                            <td>${start_date}</td>\n                        </tr>\n                        <tr>\n                            <th><strong>End Date</strong></th>\n                            <td>:</td>\n                            <td>${end_date}</td>\n                        </tr>\n                    </table>\n                </div>\n                        \n                <p>Full details, incident data and CCTV details are listed in the attached **PDF document**.</p>\n                        \n                <p>Please review this report immediately for future follow-up and preventive measures.</p>\n\n                <hr style="margin:30px 0; border:none; border-top:1px dashed #ccc;">\n\n                <p style="font-size:12px; color:#777;">\n                This email was sent automatically as a periodic report by the PPE AI Monitoring System.<br>\n                Please do not reply to this email.\n                </p>\n            </div>\n\n            <div class="footer">\n            © 2025 PPE Detection System – PT. Summit Adyawinsa Indonesia\n            </div>\n        </div>\n    </body>\n</html>	t
9	violation_monthly_recap	[RECAP] Monthly PPE Violation Report Period ${start_date} to ${end_date}	<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset="utf-8">\n        <style>\n            body { font-family: Arial, sans-serif; background:#f9f9f9; margin:0; padding:20px; }\n            .container { max-width: 680px; margin: auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }\n            .header { background: #4388CA; color: white; padding: 20px; text-align: center; }\n            .header h1 { margin:0; font-size:24px; }\n            .content { padding: 30px; line-height: 1.6; color: #333; }\n            .info-box { background:#e3f2fd; padding:15px; border-left:5px solid #2196f3; border-radius:4px; margin:20px 0; }\n            table {width:100%; border-collapse:collapse; margin:10px 0;}\n            th {text-align:left; width:35%; font-weight:600; color:#555;}\n            .footer { background:#263238; color:#cfd8dc; padding:20px; text-align:center; font-size:13px; }\n            .btn { display:inline-block; background:#4388CA; color:white; padding:12px 24px; text-decoration:none; border-radius:5px; margin-top:20px; font-weight:bold; }\n        </style>\n    </head>\n    <body>\n        <div class="container">\n            <div class="header">\n                <h1>Monthly PPE Violation Summary Report</h1>\n            </div>\n\n            <div class="content">\n                <p>Dear Mr./Ms. <strong>${full_name}</strong>,</p>\n\n                <p>Below is a summary of the Weekly PPE Violation Report for the period below, which occurred on CCTV in your area of ​​responsibility.</p>\n                    \n                <div class="info-box">\n                    <table>\n                        <tr>\n                            <th><strong>Start Date</strong></th>\n                            <td>:</td>\n                            <td>${start_date}</td>\n                        </tr>\n                        <tr>\n                            <th><strong>End Date</strong></th>\n                            <td>:</td>\n                            <td>${end_date}</td>\n                        </tr>\n                    </table>\n                </div>\n                        \n                <p>Full details, incident data and CCTV details are listed in the attached **PDF document**.</p>\n                        \n                <p>Please review this report immediately for future follow-up and preventive measures.</p>\n\n                <hr style="margin:30px 0; border:none; border-top:1px dashed #ccc;">\n\n                <p style="font-size:12px; color:#777;">\n                This email was sent automatically as a periodic report by the PPE AI Monitoring System.<br>\n                Please do not reply to this email.\n                </p>\n            </div>\n\n            <div class="footer">\n            © 2025 PPE Detection System – PT. Summit Adyawinsa Indonesia\n            </div>\n        </div>\n    </body>\n</html>	t
10	violation_custom_report	[RECAP] PPE Violation Report Period ${start_date} to ${end_date}	<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset="utf-8">\n        <style>\n            body { font-family: Arial, sans-serif; background:#f9f9f9; margin:0; padding:20px; }\n            .container { max-width: 680px; margin: auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }\n            .header { background: #4388CA; color: white; padding: 20px; text-align: center; }\n            .header h1 { margin:0; font-size:24px; }\n            .content { padding: 30px; line-height: 1.6; color: #333; }\n            .info-box { background:#e3f2fd; padding:15px; border-left:5px solid #2196f3; border-radius:4px; margin:20px 0; }\n            table {width:100%; border-collapse:collapse; margin:10px 0;}\n            th {text-align:left; width:35%; font-weight:600; color:#555;}\n            .footer { background:#263238; color:#cfd8dc; padding:20px; text-align:center; font-size:13px; }\n            .btn { display:inline-block; background:#4388CA; color:white; padding:12px 24px; text-decoration:none; border-radius:5px; margin-top:20px; font-weight:bold; }\n        </style>\n    </head>\n    <body>\n        <div class="container">\n            <div class="header">\n                <h1>PPE Violation Summary Report</h1>\n            </div>\n\n            <div class="content">\n                <p>Dear Mr./Ms. <strong>${full_name}</strong>,</p>\n\n                <p>Below is a summary of the Weekly PPE Violation Report for the period below, which occurred on CCTV in your area of ​​responsibility.</p>\n                    \n                <div class="info-box">\n                    <table>\n                        <tr>\n                            <th><strong>Start Date</strong></th>\n                            <td>:</td>\n                            <td>${start_date}</td>\n                        </tr>\n                        <tr>\n                            <th><strong>End Date</strong></th>\n                            <td>:</td>\n                            <td>${end_date}</td>\n                        </tr>\n                    </table>\n                </div>\n                        \n                <p>Full details, incident data and CCTV details are listed in the attached **PDF document**.</p>\n                        \n                <p>Please review this report immediately for future follow-up and preventive measures.</p>\n\n                <hr style="margin:30px 0; border:none; border-top:1px dashed #ccc;">\n\n                <p style="font-size:12px; color:#777;">\n                This email was sent automatically as a periodic report by the PPE AI Monitoring System.<br>\n                Please do not reply to this email.\n                </p>\n            </div>\n\n            <div class="footer">\n            © 2025 PPE Detection System – PT. Summit Adyawinsa Indonesia\n            </div>\n        </div>\n    </body>\n</html>	t
\.


--
-- Data for Name: general_settings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.general_settings (key, value, description, min_value, max_value) FROM stdin;
cleanup_interval	120	How many seconds is a violation considered “expired” and can be detected again (for the same person)	60	3600
confidence_threshold	0.25	Minimum confidence for valid detection	0.1	1
cooldown_seconds	10	The minimum time delay (seconds) for re-recording the same violation on the same object. Serves to prevent data duplication and optimize storage usage.	1	300
frame_skip	6	Take 1 frame every N frames	1	60
padding_percent	0.5	Add some percentage to bounding box enlargement when cropping violation images	0.1	2.0
queue_size	3	Maximum frames in YOLO queue	1	20
sched_cleanup_cutoff_days	60	How many days of logs and images to keep before deletion	1	365
sched_cleanup_hour	0	What time does old data cleaning take place each day (0 to 23, 0 = midnight on the new day)	0	23
sched_cleanup_minute	5	What minute is the old data cleanup performed each day (minutes 0 to 59, 0 = midnight of the new day)	0	59
sched_daily_recap_minute	0	Set specific minutes to automatically show the daily recap every hour (E.g. 15th minute)	0	59
sched_monthly_date	1	Date of month for monthly recap (1-31). If date exceeds month length, it runs on the last day.	1	31
sched_monthly_hour	7	Hour for monthly recap (0-23)	0	23
sched_monthly_minute	30	Minute for monthly recap (0-59)	0	59
sched_refresh_config_interval	10	Refresh every X minutes	1	60
sched_weekly_day	0	Day of week for weekly recap (0=Monday, 6=Sunday)	0	6
sched_weekly_hour	7	Hour for weekly recap (0-23)	0	23
sched_weekly_minute	30	Minute for weekly recap (0-59)	0	59
target_max_width	320	Maximum width of violation image (pixels)	200	1280
\.


--
-- Data for Name: object_class; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.object_class (id, name, is_violation, color_r, color_g, color_b, pair_id) FROM stdin;
1	no-helmet	t	255	112	146	6
2	no-vest	t	255	149	133	7
3	no-shoes	t	0	143	122	8
4	no-glasses	t	0	195	209	10
5	no-gloves	t	132	94	194	9
6	helmet	f	219	0	62	1
7	vest	f	170	111	90	2
8	shoes	f	80	251	223	3
9	gloves	f	219	242	255	5
10	glasses	f	179	156	208	4
\.


--
-- Data for Name: user_cctv_map; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_cctv_map (user_id, cctv_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password, full_name, email, role) FROM stdin;
fa932c3c-b911-4e20-8d61-9df209110411	admin	your_password_hash	Administrator	admin@example.com	super_admin
\.


--
-- Data for Name: violation_daily_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.violation_daily_log (id, log_date, id_cctv, id_violation, total_violation, latest_update) FROM stdin;
\.


--
-- Data for Name: violation_detection; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.violation_detection (id, id_cctv, id_violation, image, "timestamp") FROM stdin;
\.


--
-- Name: ai_models_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ai_models_id_seq', 1, false);


--
-- Name: cctv_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cctv_data_id_seq', 7, true);


--
-- Name: cctv_scheduler_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cctv_scheduler_id_seq', 1, false);


--
-- Name: email_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.email_settings_id_seq', 1, false);


--
-- Name: email_templates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.email_templates_id_seq', 1, false);


--
-- Name: object_class_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.object_class_id_seq', 1, false);


--
-- Name: violation_daily_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.violation_daily_log_id_seq', 1, false);


--
-- Name: violation_detection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.violation_detection_id_seq', 2593, true);


--
-- Name: ai_models ai_models_filename_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_filename_key UNIQUE (filename);


--
-- Name: ai_models ai_models_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_pkey PRIMARY KEY (id);


--
-- Name: cctv_data cctv_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cctv_data
    ADD CONSTRAINT cctv_data_pkey PRIMARY KEY (id);


--
-- Name: cctv_scheduler cctv_scheduler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cctv_scheduler
    ADD CONSTRAINT cctv_scheduler_pkey PRIMARY KEY (id);


--
-- Name: general_settings detection_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.general_settings
    ADD CONSTRAINT detection_settings_pkey PRIMARY KEY (key);


--
-- Name: email_templates email_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id);


--
-- Name: email_templates email_templates_template_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_template_key_key UNIQUE (template_key);


--
-- Name: cctv_scheduler no_overlap; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cctv_scheduler
    ADD CONSTRAINT no_overlap UNIQUE (cctv_id, day_of_week, start_time, end_time);


--
-- Name: object_class object_class_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.object_class
    ADD CONSTRAINT object_class_name_key UNIQUE (name);


--
-- Name: email_settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);


--
-- Name: user_cctv_map user_cctv_map_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_cctv_map
    ADD CONSTRAINT user_cctv_map_pkey PRIMARY KEY (user_id, cctv_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: violation_daily_log violation_daily_log_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.violation_daily_log
    ADD CONSTRAINT violation_daily_log_pk PRIMARY KEY (log_date, id_cctv, id_violation);


--
-- Name: object_class violation_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.object_class
    ADD CONSTRAINT violation_data_pkey PRIMARY KEY (id);


--
-- Name: violation_detection violation_detection_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.violation_detection
    ADD CONSTRAINT violation_detection_pkey PRIMARY KEY (id);


--
-- Name: idx_cctv_scheduler_lookup; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cctv_scheduler_lookup ON public.cctv_scheduler USING btree (cctv_id, day_of_week, is_active);


--
-- Name: idx_map_cctv_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_map_cctv_id ON public.user_cctv_map USING btree (cctv_id);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: cctv_scheduler cctv_scheduler_cctv_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cctv_scheduler
    ADD CONSTRAINT cctv_scheduler_cctv_id_fkey FOREIGN KEY (cctv_id) REFERENCES public.cctv_data(id) ON DELETE CASCADE;


--
-- Name: object_class object_class_pair_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.object_class
    ADD CONSTRAINT object_class_pair_id_fkey FOREIGN KEY (pair_id) REFERENCES public.object_class(id);


--
-- Name: user_cctv_map user_cctv_map_cctv_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_cctv_map
    ADD CONSTRAINT user_cctv_map_cctv_id_fkey FOREIGN KEY (cctv_id) REFERENCES public.cctv_data(id) ON DELETE CASCADE;


--
-- Name: user_cctv_map user_cctv_map_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_cctv_map
    ADD CONSTRAINT user_cctv_map_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: violation_daily_log violation_daily_log_id_cctv_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.violation_daily_log
    ADD CONSTRAINT violation_daily_log_id_cctv_fkey FOREIGN KEY (id_cctv) REFERENCES public.cctv_data(id);


--
-- Name: violation_daily_log violation_daily_log_id_violation_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.violation_daily_log
    ADD CONSTRAINT violation_daily_log_id_violation_fkey FOREIGN KEY (id_violation) REFERENCES public.object_class(id);


--
-- Name: violation_detection violation_detection_id_cctv_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.violation_detection
    ADD CONSTRAINT violation_detection_id_cctv_fkey FOREIGN KEY (id_cctv) REFERENCES public.cctv_data(id);


--
-- Name: violation_detection violation_detection_id_violation_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.violation_detection
    ADD CONSTRAINT violation_detection_id_violation_fkey FOREIGN KEY (id_violation) REFERENCES public.object_class(id);


--
-- PostgreSQL database dump complete
--

\unrestrict wBeyH8wdsT4au7bCSBJCyaQtTMuL2h6ElDwbMQQljqSUZc78qeFnm4wvzuoJ3C1

